### PR TITLE
feat(github-ci): add docker image build

### PR DESCRIPTION
**Pull request by Nefelim4ag**
Added CI to build a docker image on the tag

### CODE REVIEW

**Comment by bdovaz** [comment]
@Nefelim4ag you should also generate an image for arm64 because it is perfectly compatible.

**Comment by Nefelim4ag** [comment]
Yep, your point is correct, but I tried to do that and got a compilation error on arm, so I only suggest that will works
https://github.com/Nefelim4ag/UnityNuGet/actions/runs/4378154627/jobs/7662531497#step:7:413

**Comment by bdovaz** [comment]
Related https://github.com/dotnet/sdk/issues/27190

**Comment by bdovaz** [comment]
@Nefelim4ag ping!

It is now possible to do so: https://devblogs.microsoft.com/dotnet/improving-multiplatform-container-support/#build-net-images-for-any-architecture

**Comment by Nefelim4ag** [comment]
buildx & github use buildx underneath, but i will add arm64 to test

**Comment by Nefelim4ag** [comment]
And same, https://github.com/Nefelim4ag/UnityNuGet/actions/runs/5278228406/jobs/9547276960#step:7:448

**Comment by Nefelim4ag** [comment]
@bdovaz I switched the build to 8.0-preview and it looks like it fixed the problem.
I tested the image on the amd64 & arm64 machines at least it runs and looks like works.

**Comment by bdovaz** [comment]
@Nefelim4ag you forgot to use the `TARGETARCH` parameter, try it now with the changes I have added.

**Comment by Nefelim4ag** [comment]
Yep, it's works
https://github.com/Nefelim4ag/UnityNuGet/actions/runs/5858676520/job/15883096146

**Pull request merged**
