### PR TITLE
TestCaseSource on RegistryTests

### PR DESCRIPTION
**Pull request by Thaina**
This is not request for registry but propose change on the RegistryTests so each registry entry would be tested separately for each case and have explicit case entry for easier investigating and rerun

### CODE REVIEW

**Comment by bdovaz** [comment]
@Thaina please merge master in your branch

**Comment by bdovaz** [comment]
Can you resolve the conflicts? Thanks!

**Comment by Thaina** [comment]
@bdovaz resolved

**Comment by bdovaz** [comment]
- Restore the `Ensure_Do_Not_Exceed_The_Maximum_Number_Of_Allowed_Versions` test.
- Could it be that in some file you have changed EOLs? Because I see more changes than it should.

**Comment by Thaina** [comment]
@bdovaz

- As I have mention, `Ensure_Do_Not_Exceed_The_Maximum_Number_Of_Allowed_Versions` just use `Assert.Inconclusive` So it should be suffice with just `Warn.If`
https://github.com/xoofx/UnityNuGet/blob/ed730879d7919e1cc39b7ed8c05b95f30624f8d4/src/UnityNuGet.Tests/RegistryTests.cs#L237-L240

Not only it was `Ensure_Do_Not_Exceed_The_Maximum_Number_Of_Allowed_Versions` redundantly load whole registry in exact same manner as `Ensure_Min_Version_Is_Correct_Ignoring_Analyzers_And_Native_Libs`, it also bunching all of the lib that not pass the test into one long array. I think it would be more beneficial to separate warning into each of the testcase

- Have you use `Hide WhiteSpaces` already?
image

**Comment by Thaina** [comment]
> have you checked that you haven't changed any EOL?

I don't really sure, I use vscode and I don't know if it saved with difference EOL than the source or not and it also not report any change except 2 lines of code that it trimming whitespace automatically

**Comment by Thaina** [comment]
@bdovaz If the EOL was changed can you edit that?

**Comment by bdovaz** [comment]
@Thaina please don't mix PRs.... You have put changes in scripts that are not test scripts.

**Comment by Thaina** [comment]
@bdovaz Could you please just merge it now already

**Comment by bdovaz** [comment]
@Thaina I have merge a branch that normalizes all the files to LF, merge the main branch again and see if we have everything ok.

**Comment by Thaina** [comment]
@bdovaz Could you please just merge it now already

**Comment by Thaina** [comment]
From the last failed ci

```
2024-12-23T04:24:31.5108329Z Unexpected error NuGet.Protocol.Core.Types.FatalProtocolException: Unable to find version '4.9.0' of package 'Roslynator.Analyzers'.
2024-12-23T04:24:31.5109543Z   C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\: Package 'Roslynator.Analyzers.4.9.0' is not found on source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\'.
2024-12-23T04:24:31.5110719Z   https://api.nuget.org/v3/index.json: Error downloading 'Roslynator.Analyzers.4.9.0' from 'https://api.nuget.org/v3-flatcontainer/roslynator.analyzers/4.9.0/roslynator.analyzers.4.9.0.nupkg'.
2024-12-23T04:24:31.5111521Z   End of Central Directory record could not be found.
```

I don't think this related to my change

**Pull request merged**
