### PR TITLE
Extensible configuration

### PR DESCRIPTION
**Pull request by bdovaz**
@xoofx This PR is motivated by 2 reasons:
- Unity is including support for .NET Standard 2.1 in version 2021.2b.
- The server should be more configurable with environment variables to be able to serve custom NuGet repositories.

**Configuration**

The following variables have been exposed:
- Server root http url: {azure websites url}
- Unity scope: org.nuget
- Minimum Unity version: 2019.1
- Package name NuGet PostFix: " (NuGet)"
- Packages root folder path: unity_packages. In the development environment it is relative to the binary folder and in the production environment if an absolute path is provided it will take that one and if not it will add it to the working directory of the application.
- Packages Update Interval: 10 minutes
- Target Framework: netstandard2.0
- Unity define constraint: NET_STANDARD_2_0

They have been exposed through the Microsoft.Extensions.Configuration API which is very versatile as it can be configured in many ways like with a json file or with environment variables (useful with a Docker container).

I have configured in the appsettings.json file the default values as they were so that there are no breaking changes.

**Configuration validation**

Added Options.DataAnnotations API to validate the configuration.

**Dependencies**

Dependencies have been updated for all projects.

**Docker**

Complete example with all the configuration that can be modified and making an example of raising a container for .NET Standard 2.1.

### CODE REVIEW

**Comment by xoofx** [comment]
@bdovaz I have implemented support for .NETStandard 2.1 on top of your PR. 
Do you think you could take the time on your side to check locally if it is working well with Unity before I deploy?

**Comment by bdovaz** [comment]
@xoofx of course! I will give you feedback as soon as I can.

Thank you very much for your work.

**Comment by bdovaz** [comment]
@xoofx some feedback! I have seen 2 things that have blocked me to continue testing.

When a package is found that has multitarget I see that a folder is created for each one as for example: netstandard2.0 and netstandard2.1. 

1. The problem is that the corresponding *.meta is not created for each folder. Example: netstandard2.0.meta

image

2. It seems that the same guid is reused for the dll and xml meta files.

image

**Comment by xoofx** [comment]
@bdovaz It should be fixed. Could you try again with latest master?

**Comment by bdovaz** [comment]
@xoofx I have tested it again and the problems from before are solved but I have found a new one that I already commented in the thread "Unity Future .NET Development Status".

The problem is when there are packages that only target 2.0 and happen to include dependencies that are already included in 2.1. This in a .NET Core / .NET 5 project solves it perfectly but in Unity it brings the conflicting dependency (System.Threading.Tasks.Extensions) and collides with "netstandard".

https://www.nuget.org/packages/System.Text.Json

https://www.nuget.org/packages/System.Threading.Tasks.Extensions/

image

image

**Comment by xoofx** [comment]
> The problem is when there are packages that only target 2.0 and happen to include dependencies that are already included in 2.1.

Indeed, we actually discussed about this particular issue in general in Unity (not just for the case of UnityNuGet) and it will require a special handling in Unity that we need to bring.
But for UnityNuGet I can filter them out with a whitelist, so I will try that tomorrow, let's see

**Comment by bdovaz** [comment]
Understood! The option of special handling in Unity is the best but I imagine that it will not be in the short term.

In the meantime we can workaround it as you say.

**Comment by xoofx** [comment]
I pushed a fix for the conflicting assemblies. Let me know if this is working.

**Comment by bdovaz** [comment]
@xoofx now I have this problem:

image

The behavior is as expected according to the changes you have made but it seems like System.Buffers, System.Memory and System.Threading.Tasks.Extensions are not included although it is in the installation directory of Unity.

For example:

image

**Comment by xoofx** [comment]
Ok, this one is a bug in Unity. I will have to come back to the teams handling this.

**Pull request merged**
