### PR TITLE
Bump ComradeVanti.CSharpTools.Opt

### PR DESCRIPTION
**Pull request by ComradeVanti**
Bump version from 1.0.2 to 2.1.0

### CODE REVIEW

**Comment by KuraiAndras** [comment]
Why did you bump this? Do the versions between 1.0.2 and 2.1.0 have problems with Unity?

**Comment by ComradeVanti** [comment]
@KuraiAndras No, just some new features

**Comment by KuraiAndras** [comment]
Then this change is not needed. The versions in registry.json specify the minimum versions supported by unity, and it will publish all versions up to the latest available. For example if you look at the `Microsoft.Extensions.*`  packages you can see that the registry references the `2.0.0` version, but in the package manager you can access later versions.

If you can't see the current version in the package manager it might mean that the azure-hosted server has some dependency problem and can't update packages.

**Comment by ComradeVanti** [comment]
Oops my bad. Thanks for the info. I think I can't see 2.1.0 yet because I pushed it to nuget like 20mins ago

**Pull request closed without merging**
