### PR TITLE
Avoid fetching NuGet packages if the cache is up-to-date

### PR DESCRIPTION
**Pull request by xoofx**
cc: @bdovaz 

I have implemented the early cache skip as suggested in [comment](https://github.com/xoofx/UnityNuGet/issues/175#issuecomment-1435967067)

It seems to work locally (but tested only on a limited set of packages). Gonna try this on this CI before merging.

### CODE REVIEW

**Comment by xoofx** [comment]
One change to your PR is that I'm not delete the NuGet folder if it is not running on Azure because when I started to run it locally, it deleted my NuGet global packages cache, and VS started to get confused 😅 
Let's see if it if ok to keep that rule or we need another one (e.g we might still want to delete on GitHub CI)

**Comment by bdovaz** [comment]
@xoofx CI passed! 🎉🎉

**Comment by bdovaz** [comment]
@xoofx seems to be operational again! I'll be using it a lot today, I'll let you know if I see anything unusual.

Thanks for everything Alexandre!

**Comment by xoofx** [comment]
Yeah, it is taking less than 10min now to update, so that's a big gain! Let's see how it goes 😎 🤞

**Pull request merged**
