### PR TITLE
Dapplo.Windows.User32-1.0.26, Dapplo.Windows.Input-1.0.26

### PR DESCRIPTION
**Pull request by IvanMurzak**
> The NuGet package needs to respect a few constraints in order to be listed in the curated list:
> - [x] Add a link to the NuGet package: https://www.nuget.org/packages/Dapplo.Windows.User32
> - [x] It must have non-preview versions (e.g 1.0.0 but not 1.0.0-preview.1)
> - [x] It must provide .NETStandard2.0 assemblies as part of its package
> - [x] The lowest version added must be the lowest .NETStandard2.0 version available
> - [x] The package has been tested with the Unity editor 
> - [x] The package has been tested with a Unity standalone player
>   - if the package is not compatible with standalone player, please add a comment to a Known issues section to the top level readme.md
> - [x] All package dependencies with .NETStandard 2.0 target must be added to the PR (respecting the same rules above)
>   - Note that if a future version of the package adds a new dependency, this dependency will have to be added manually as well
> 
> Note: The server will be updated only when a new version tag is pushed on the main branch, not necessarily after merging this pull-request.

### CODE REVIEW

**Comment by IvanMurzak** [comment]
Does anybody know how to set the minimum version? `Dapplo` packages should have the minimum version of 1.0.26. This test failed because it believes it should be 0.7.x version. But this version won't work.

**Comment by bdovaz** [comment]
Why 0.7 won't work?

**Comment by IvanMurzak** [comment]
> Why 0.7 won't work?

Everything below 1.0.26 has non-resolvable for Unity dependencies. That is [Microsoft.Windows.Compatibility](https://www.nuget.org/packages/Microsoft.Windows.Compatibility/6.0.0#dependencies-body-tab). This one has first of all tons of dependencies. Secondly, it has one dependency that doesn't work for sure. I know that because I tried to use it in Unity, and even tried to add it to UnityNuGet. It doesn't work in Unity's Mono environment. The package is [System.Speech](https://www.nuget.org/packages/System.Speech/).

**Comment by bdovaz** [comment]
To allow another minimum version and not to fail the test you have to add an entry in this list with a comment:

https://github.com/xoofx/UnityNuGet/blob/7afa3f07d49b1d9cbf4a583962cb23bb443459e8/src/UnityNuGet.Tests/RegistryTests.cs#L110

**Comment by IvanMurzak** [comment]
> To allow another minimum version and not to fail the test you have to add an entry in this list with a comment:
> 
> https://github.com/xoofx/UnityNuGet/blob/7afa3f07d49b1d9cbf4a583962cb23bb443459e8/src/UnityNuGet.Tests/RegistryTests.cs#L110

Thank you. Will do. I see it already contains my addition of EntityFramework 😅

**Comment by IvanMurzak** [comment]
@bdovaz would you mind me to create a dedicated pull request with updated packages.json format with ability to set minimum and maximum versions in the JSON. 

Such as:
```json
  "Dapplo.Windows.Input": {
    "listed": true,
    "version": "[1.0.26"
  },
  "Dapplo.Windows.Input": {
    "listed": true,
    "version": "[1.0.26 <-> 2.0.0]"
  },
```

`"version": "[1.0.26"` `[` - means the barrier, so can't get lower than this
`"version": "[1.0.26 <-> 2.0.0]"` `]` - means the barrier, can't get bigger than this value. `<->` - means everything in between.
`"version": "[1.0.26, 1.0.28 <-> 2.0.0]"` - means not lower than 1.0.26, skip all versions between 1.0.26 and 1.0.28. Take all versions between 1.0.28 and 2.0.0.

We can discuss the format and options in detail. But it looks more flexible in comparison with having a list of constants that just disable Unit Test execution.

**Pull request merged**
