### PR TITLE
Add SignalR client with MessagePack

### PR DESCRIPTION
**Pull request by bdovaz**

### CODE REVIEW

**Comment by xoofx** [comment]
Just to make sure, have you tested these libraries with Unity? Do they work well in both editor and standalone player mode?

**Comment by bdovaz** [comment]
We have been using these libraries for at least 2 years without any problem on the following platforms using IL2CPP (it may require link.xml tweaks): Windows, macOS, UWP, Android, iOS.

On WebGL it does NOT work due to the fact that it creates threads but "someday" this will change and it will start working.

**Comment by xoofx** [comment]
Can you fix the conflict on the file?

**Comment by xoofx** [comment]
@bdovaz and  @hybridherbst, are you done with the update you wanted to make on the registry? (If yes, I will push the new server tomorrow)

**Pull request merged**
