### PR TITLE
chore: add new version for System.Runtime.CompilerServices.Unsafe and Google.Prorobuf

### PR DESCRIPTION
**Pull request by felipejfc**
New versions for existing packages.

### CODE REVIEW

**Comment by bdovaz** [comment]
@felipejfc I don't understand this PR, with this change you are not adding those versions, you are limiting the range of versions:

https://learn.microsoft.com/en-us/nuget/concepts/package-versioning#version-ranges

The new versions resolve themselves in a 10 minute interval.

**Comment by felipejfc** [comment]
What I wanted to achieve was to add a new version of Protobuf nuget lib in the repo. Currently we only have 3.8.0 available, however this is super old, the official package is already at version 3.24.3.
Did I do it wrong? What would be the right approach?

**Comment by bdovaz** [comment]
@felipejfc I don't understand your problem, they are available in the feed:

https://unitynuget-registry.azurewebsites.net/org.nuget.google.protobuf

https://unitynuget-registry.azurewebsites.net/org.nuget.system.runtime.compilerservices.unsafe

image

**Comment by felipejfc** [comment]
Ah I thought they werent! thanks!

**Pull request closed without merging**
