### PR TITLE
Update registry.json

### PR DESCRIPTION
**Pull request by MonoLogueChi**
add zlogger and zstring

zlogger   https://www.nuget.org/packages/ZLogger
Utf8StringInterpolation  https://www.nuget.org/packages/Utf8StringInterpolation/
zstring  https://www.nuget.org/packages/ZString/

> The NuGet package needs to respect a few constraints in order to be listed in the curated list:
> - [x] Add a link to the NuGet package: https://www.nuget.org/packages/XXX
> - [x] It must have non-preview versions (e.g 1.0.0 but not 1.0.0-preview.1)
> - [x] It must provide .NETStandard2.0 assemblies as part of its package
> - [x] The lowest version added must be the lowest .NETStandard2.0 version available
> - [x] The package has been tested with the Unity editor 
> - [x] The package has been tested with a Unity standalone player
>   - if the package is not compatible with standalone player, please add a comment to a Known issues section to the top level readme.md
> - [x] All package dependencies with .NETStandard 2.0 target must be added to the PR (respecting the same rules above)
>   - Note that if a future version of the package adds a new dependency, this dependency will have to be added manually as well
> 
> Note: The server will be updated only when a new version tag is pushed on the main branch, not necessarily after merging this pull-request.

### CODE REVIEW

**Comment by bdovaz** [comment]
@MonoLogueChi why did you close it? For compatibility? Just curious in case someone wants to use this package.

**Comment by MonoLogueChi** [comment]
> @MonoLogueChi why did you close it? For compatibility? Just curious in case someone wants to use this package.

Because I don't know if I should modify this PR. Utf8StringInterpolation, which supports the minimum version of .NET Standard 2.0, depends on PolySharp, which is not a .NET Standard 2.0 package. The latest version of Utf8StringInterpolation removes this dependency, but does not meet the requirements for supporting the minimum version of .NET Standard 2.0.

**Comment by MonoLogueChi** [comment]
> @MonoLogueChi why did you close it? For compatibility? Just curious in case someone wants to use this package.

I've been modifying my logging module recently and want to try using Zlogger instead of the logs I used to assemble manually. Maybe others will have the same use.

**Comment by MonoLogueChi** [comment]
Can UnityNuGet ignore non-existent dependencies? If so, I can resubmit the PR after solving other problems.

**Comment by bdovaz** [comment]
1. Add "Utf8StringInterpolation" with "1.3.1" because as you say it is the first version that does not depend on "PolySharp".
2. Add "ZLogger" with "2.0.1" which is the first one that depends on "Utf8StringInterpolation" >= 1.3.1.
3. Add exclusions of those 2 with a comment why so you don't get test failures: https://github.com/xoofx/UnityNuGet/blob/22dc797afe0b3f87466c0fc17416c95b98633ab3/src/UnityNuGet.Tests/RegistryTests.cs#L109

**Pull request closed without merging**
